import type { Metadata } from 'next';
import { Inter, Tektur, Nunito, Dosis, Mukta } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Navbar from './components/navbar/Navbar';
import Footer from './components/footer/Footer';

const inter = Inter({ subsets: ['latin'] });
const tektur = Tektur({
  subsets: ['latin'],
  weight: '500',
  variable: '--font-tektur',
});
const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
});
const dosis = Dosis({
  subsets: ['latin'],
  variable: '--font-dosis',
});
const mukta = Mukta({
  weight: '300',
  subsets: ['latin'],
  variable: '--font-mukta',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'relative h-full font-sans antialiased',
          inter.className,
          tektur.variable,
          nunito.variable,
          dosis.variable,
          mukta.variable
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
